import type { Metadata } from 'next'
import Providers from './providers'
import { playfair, atkinsonNext } from '@/app/fonts'
import Navbar from '@/components/layouts/header/Navbar'
import Footer from '@/components/layouts/footer/Footer'
import { Analytics } from '@vercel/analytics/react'
// import './globals.css'
import '@/styles/index.scss'



export const metadata: Metadata = {
  title: 'Escape from Eden',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // This is a Server Component by default
  return (
    <html lang='en' suppressHydrationWarning>
      <body suppressHydrationWarning className={`${playfair.variable} ${atkinsonNext.variable} antialiased`}>
        <Providers>
          <Analytics />
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
