import type { Metadata } from 'next'
import Providers from './providers'
import { playfair, atkinsonNext, atkinsonMono } from '@/app/fonts'
import Header from '@/components/layouts/header/Header'
import Footer from '@/components/layouts/footer/Footer'
import { Analytics } from '@vercel/analytics/react'
import '@/styles/index.scss'

export const metadata: Metadata = {
  title: 'Escape from Eden',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // This is a Server Component by default
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${playfair.variable} ${atkinsonNext.variable} ${atkinsonMono.variable} antialiased`}
      >
        <Providers>
          <Analytics />
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
